services:
    postgres:
        container_name: postgres_container
        image: postgres:13
        ports:
            - 5434:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: open-health-log
        volumes:
            - ./db:/var/lib/postgresql/data
